import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
const root = path.resolve(new URL('..', import.meta.url).pathname);
const config = fs.readFileSync(path.join(root,'js/config.js'),'utf8');
const app = fs.readFileSync(path.join(root,'js/app.js'),'utf8');
const index = fs.readFileSync(path.join(root,'index.html'),'utf8');
const release = fs.readFileSync(path.join(root,'js/release.js'),'utf8');
const sw = fs.readFileSync(path.join(root,'sw.js'),'utf8');
assert.match(config, /APP_VERSION = '1\.0\.[0-9]+'/);
assert.match(app, /registerRoute\('release', releasePage\)/);
assert.match(app, /Welcome to Democracy Web 1\.0/);
assert.match(app, /copy-diagnostic-report/);
assert.match(app, /download-diagnostic-report/);
assert.match(app, /unhandledrejection/);
assert.match(index, /data-route="release"/);
assert.match(release, /RELEASE_CHANNEL = 'stable'/);
assert.match(release, /\[redacted\]/);
assert.ok(fs.existsSync(path.join(root,'CHANGELOG.md')));
assert.ok(fs.existsSync(path.join(root,'RELEASE_NOTES.md')));
assert.match(sw, /democracy-web-v10[0-9]+/);
console.log('PASS Phase 31–33 release checks');
